#!/usr/bin/bash

# Setup git's prompt options.
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWSTASHSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWCONFLICTSTATE="yes"
GIT_PS1_SHOWUPSTREAM="auto"
GIT_PS1_SHOWCOLORHINTS=true

# Start by sourcing the main profile in order to maintain some defaults.
source /etc/bash.bashrc

# Make a better PS1 line.
export PS1='\[\033]0;$TITLEPREFIX:$PWD\007\]\n\[\033[32m\]\u\[\033[0m\]@\[\033[32m\]\h \[\033[33m\]\w\[\033[0m\]`__git_ps1`\[\033[0m\]\n\$ '

# Load in some of our aliases.
. ~/dotfiles/bash/bash_aliases
