#!/bin/bash

path=/var/tmp

scrot $path/shot.png
convert $path/shot.png -blur 0x20 $path/shot-blurred.png
convert -size 1920x1080 xc:transparent -font Courier-bold -pointsize 15 -fill Gray -draw "text 30,1045 'Away since `date`'" $path/watermark.png
composite -dissolve 80% -quality 100 $path/watermark.png $path/shot-blurred.png $path/final.png
i3lock -u -i $path/final.png
rm $path/shot-blurred.png $path/watermark.png $path/final.png

