#!/bin/bash

### ~/.bash_aliases
### Some handy aliases for your shell.
###
### Author: Nathan Campos <nathan@innoveworkshop.com>

# Handy ls aliases.
alias ls='ls -F'
alias ll='ls -la'
alias la='ls -AF'

# Handy git aliases.
alias gs='git status'
alias gc='git commit'
alias gps='git push'
alias gpl='git pull'

# Making things colorful.
if [ -x /usr/bin/dircolors ]; then
	test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	alias ls='ls --color=auto'
	alias dir='dir --color=auto'
	alias vdir='vdir --color=auto'

	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
fi

