#!/bin/bash

### ~/.bash_profile
### Bash login profile configuration.
###
### Author: Nathan Campos <nathan@innoveworkshop.com>

# Don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# Append to the history file, don't overwrite it.
shopt -s histappend

# Have a nice and long history.
HISTSIZE=10000
HISTFILESIZE=10000

# Update the values of LINES and COLUMNS after each command if necessary.
shopt -s checkwinsize

# Sets the fancy color terminal variable if we can handle it.
case "$TERM" in
	xterm-color|*-256color) color_prompt=yes;;
esac

# Setup a fancy prompt.
if [ "$color_prompt" = yes ]; then
	export PS1='\[\033[00m\][\[\033[01;32m\]\u@\h \[\033[01;34m\]\w\[\033[00m\]]\$ '
else
	export PS1='[\u@\h \w]\$ '
fi

# Make sure our scripts and /sbin are in the system PATH.
export PATH="/sbin:$HOME/dotfiles/scripts:$PATH"

# Enable the handy tab completions.
if [ -f /usr/share/bash-completion/bash_completion ]; then
	. /usr/share/bash-completion/bash_completion
elif [ -f /etc/bash_completion ]; then
	. /etc/bash_completion
fi

# Setup aliases.
if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi

# Load up the computer-specific Bash configuration.
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# Setup some pretty things if we aren't in a dumb terminal.
if [ "$TERM" != "dumb" ]; then
	# Fix the base16 colors up.
	BASE16_SHELL="$HOME/.config/base16-shell/"
	if [ -n "$PS1" ]; then
		if [ -s "$BASE16_SHELL/profile_helper.sh" ]; then
			eval "$("$BASE16_SHELL/profile_helper.sh")"
		fi
	fi

	# Show a pretty welcome message.
	if [ -x "$(command -v neofetch)" ]; then
		neofetch
	fi
fi

