#!/bin/bash

### ~/.bash_profile
### Bash login profile configuration.
###
### Author: Nathan Campos <nathan@innoveworkshop.com>

# Load our pre-profile source private customization.
if [ -f ~/.bash_private_preload ]; then
	source ~/.bash_private_preload
else
	# Deal with some defaults.
	export PS1HOSTCOLOR="\[\033[01;33m\]"
fi

# Get which system we are currently dealing with.
OS_NAME=`(uname -s) 2>/dev/null`

# Don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# Append to the history file, don't overwrite it.
shopt -s histappend

# Have a nice and long history.
HISTSIZE=10000
HISTFILESIZE=10000

# Set some sane default applications.
export EDITOR=vim
export VISUAL=${EDITOR}
export PAGER=less
export LESS=FRX

# Update the values of LINES and COLUMNS after each command if necessary.
shopt -s checkwinsize

# Setup git integration.
if [ -f ~/dotfiles/bash/ext/git-completion.bash ]; then
	source ~/dotfiles/bash/ext/git-completion.bash
fi
if [ -f ~/dotfiles/bash/ext/git-prompt.sh ]; then
	GIT_PS1_SHOWDIRTYSTATE=true
	GIT_PS1_SHOWSTASHSTATE=true
	GIT_PS1_SHOWUNTRACKEDFILES=true
	GIT_PS1_SHOWUPSTREAM="auto"
	GIT_PS1_SHOWCOLORHINTS=true
	source ~/dotfiles/bash/ext/git-prompt.sh
fi

# Setup fancyness according to capabilities.
case "$TERM" in
	"dumb")
		export PS1="$ "
		;;
	xterm*|rxvt*|eterm*|screen*)
		export PROMPT_COMMAND='__git_ps1 "\[\033[00m\][$PS1HOSTCOLOR\u\[\033[00m\]@$PS1HOSTCOLOR\h \[\033[01;34m\]\w\[\033[00m\]]" "\$ " " (%s)"'
		;;
esac

# Add iTerm 2 integration.
if [ "$OS_NAME" = "Darwin" ]; then
	test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
fi

# Add MacPorts to the system PATH.
if [ "$OS_NAME" = "Darwin" ]; then
	export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
	export MANPATH="/opt/local/share/man:$MANPATH"
fi

# Ensure Python packages are in our system PATH.
if [ command -v python3 >/dev/null 2>&1 ]; then
	export PATH="`python3 -m site --user-base`/bin:$PATH"
fi

# Ensure Perl's packages are in our system PATH.
export PATH="`perl -MConfig -e 'print $Config{installsitebin}'`:$PATH"

# Make sure our scripts, /usr/local/bin, and /sbin are in the system PATH.
export PATH="/usr/local/sbin:/usr/local/bin:/sbin:/usr/local/bin:$HOME/dotfiles/scripts:$PATH"

# Enable the handy tab completions.
if [ -f /usr/share/bash-completion/bash_completion ]; then
	. /usr/share/bash-completion/bash_completion
elif [ -f /etc/bash_completion ]; then
	. /etc/bash_completion
elif [ -f /opt/local/etc/profile.d/bash_completion.sh ]; then
	. /opt/local/etc/profile.d/bash_completion.sh
elif [ -f /usr/local/share/bash-completion/bash_completion.sh ]; then
	. /usr/local/share/bash-completion/bash_completion.sh
elif [ -r /opt/local/share/bash-completion/bash_completion ]; then
	. /opt/local/share/bash-completion/bash_completion
fi

# Setup aliases.
if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi

# Load up the computer-specific Bash configuration.
if [ -f ~/.bash_private ]; then
	source ~/.bash_private
fi

# Setup some pretty things if we aren't in a dumb terminal.
if [ "$TERM" != "dumb" ]; then
	# Show a pretty welcome message.
	if [ -x "$(command -v neofetch)" ]; then
		neofetch
	fi
fi

