#!/bin/bash

### ~/.bash_aliases
### Some handy aliases for your shell.
###
### Author: Nathan Campos <nathan@innoveworkshop.com>

# Get which system we are currently dealing with.
OS_NAME=`(uname -s) 2>/dev/null`

# Making things colorful.
if [ -x /usr/bin/dircolors ]; then
	test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	if [ "$OS_NAME" = "Darwin" ]; then
		alias ls='ls -G'
		alias ll='ls -Gla'
	else
		alias ls='ls --color=auto'
		alias dir='dir --color=auto'
		alias vdir='vdir --color=auto'
	fi

	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
fi

# Handy ls aliases.
if [ "$OS_NAME" = "Darwin" ]; then
	alias ls='ls -GF'
	alias ll='ls -Gla'
	alias la='ls -GAF'
else
	alias ls='ls -F --color=auto'
	alias ll='ls -la --color=auto'
	alias la='ls -AF --color=auto'
fi

# Handy git aliases.
alias gs='git status'
alias gc='git commit'
alias gcm='git commit -m'
alias ga='git add'
alias gdf='git diff'
alias gps='git push'
alias gpl='git pull'

# Pretty cat.
if [ -x "$(command -v batcat)" ]; then
	alias bat='batcat'
fi

# Handy clipboard copying.
alias xclip='xclip -selection c'

